version: '3.8'

services:
  # Official Calibre-Web-Automated
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: cwa-official
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    ports:
      - "8083:8083"
    volumes:
      # CWA Configuration (contains app.db for CWA settings and users)
      - cwa-config:/config
      
      # Calibre Library (contains metadata.db and book files)
      - cwa-library:/calibre-library
      
      # Book ingest folder (files here get processed and deleted)
      - cwa-ingest:/cwa-book-ingest
      
      # Optional: Mount your existing library if you have one
      # - /path/to/existing/calibre/library:/calibre-library
      
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - cwa-network

  # Our Flask API and Modern Frontend
  cwa-downloader-api:
    build:
      context: .
      dockerfile: Dockerfile.fullstack
    container_name: cwa-downloader-api
    environment:
      - FLASK_PORT=8084
      - FLASK_HOST=0.0.0.0
      - DEBUG=false
      - APP_ENV=production
      - LOG_LEVEL=INFO
      - ENABLE_LOGGING=true
      - BOOK_LANGUAGE=en
      - USE_BOOK_TITLE=true
      - MAX_CONCURRENT_DOWNLOADS=3
      - TZ=America/New_York
      
      # Database paths (shared with CWA)
      - CWA_DB_PATH=/app/shared-data/cwa.db
      - CALIBRE_DB_PATH=/app/shared-data/calibre-library
      
      # CWA connection (internal network)
      - CWA_BASE_URL=http://calibre-web-automated:8083
      - CWA_USERNAME=admin
      - CWA_PASSWORD=admin123
      
    ports:
      - "8084:8084"
    volumes:
      # Our app's database and logs
      - cwa-downloader-data:/app/data
      - cwa-downloader-logs:/app/logs
      
      # Shared access to CWA's data (read-only for safety)
      - cwa-config:/app/shared-data/config:ro
      - cwa-library:/app/shared-data/calibre-library:ro
      
      # Ingest directory (shared write access)
      - cwa-ingest:/app/ingest
      
    restart: unless-stopped
    depends_on:
      - calibre-web-automated
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - cwa-network

  # Nginx reverse proxy (optional - for single entry point)
  nginx-proxy:
    image: nginx:alpine
    container_name: cwa-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - calibre-web-automated
      - cwa-downloader-api
    restart: unless-stopped
    networks:
      - cwa-network

volumes:
  # CWA Data
  cwa-config:
    driver: local
  cwa-library:
    driver: local
  cwa-ingest:
    driver: local
    
  # Our App Data
  cwa-downloader-data:
    driver: local
  cwa-downloader-logs:
    driver: local

networks:
  cwa-network:
    driver: bridge
