version: '3.8'

services:
  # All-in-one CWA Book Downloader with built-in React frontend
  cwa-book-downloader:
    build:
      context: .
      dockerfile: Dockerfile.fullstack
    container_name: cwa-book-downloader
    restart: unless-stopped
    
    # Port Configuration
    ports:
      - "${CWA_BD_PORT:-8084}:8084"
    
    # Environment Variables - All configurable for Unraid
    environment:
      # Flask Application Settings
      - FLASK_PORT=8084
      - FLASK_HOST=0.0.0.0
      - APP_ENV=${APP_ENV:-production}
      - DEBUG=${DEBUG:-false}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - ENABLE_LOGGING=${ENABLE_LOGGING:-true}
      
      # Authentication & Database
      - CWA_DB_PATH=${CWA_DB_PATH:-/config/app.db}
      - DISABLE_AUTH=${DISABLE_AUTH:-false}
      
      # CWA Integration (Required)
      - CWA_BASE_URL=${CWA_BASE_URL}
      - CWA_USERNAME=${CWA_USERNAME:-admin}
      - CWA_PASSWORD=${CWA_PASSWORD}
      
      # Book Download Settings
      - BOOK_LANGUAGE=${BOOK_LANGUAGE:-en}
      - USE_BOOK_TITLE=${USE_BOOK_TITLE:-true}
      - MAX_CONCURRENT_DOWNLOADS=${MAX_CONCURRENT_DOWNLOADS:-3}
      - DOWNLOAD_PROGRESS_UPDATE_INTERVAL=${DOWNLOAD_PROGRESS_UPDATE_INTERVAL:-5}
      - MAX_RETRY=${MAX_RETRY:-10}
      - DEFAULT_SLEEP=${DEFAULT_SLEEP:-5}
      
      # Anna's Archive Settings
      - AA_DONATOR_KEY=${AA_DONATOR_KEY}
      - AA_BASE_URL=${AA_BASE_URL:-auto}
      
      # Network & Proxy Settings
      - USE_CF_BYPASS=${USE_CF_BYPASS:-true}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - CUSTOM_DNS=${CUSTOM_DNS}
      - USE_DOH=${USE_DOH:-false}
      - DOH_SERVER=${DOH_SERVER}
      
      # System Settings
      - TZ=${TZ:-America/New_York}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      
      # Directory Paths (Internal - mapped via volumes)
      - INGEST_DIR=/ingest
      - LOG_ROOT=/logs
      - TMP_DIR=/tmp/cwa-book-downloader
      
    # Volume Mappings - All configurable for Unraid
    volumes:
      # Configuration directory (contains app.db for authentication)
      - "${CONFIG_DIR}:/config"
      
      # Calibre library directory (contains metadata.db and books)
      - "${CALIBRE_LIBRARY_DIR}:/calibre-library"
      
      # Book ingest directory (where downloaded books are placed)
      - "${INGEST_DIR}:/ingest"
      
      # Application logs
      - "${LOGS_DIR:-./logs}:/logs"
      
      # Application data (internal database, cache, etc.)
      - "${DATA_DIR:-./data}:/app/data"
      
      # Temporary files
      - "${TEMP_DIR:-/tmp/cwa-book-downloader}:/tmp/cwa-book-downloader"
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Resource limits (optional - can be configured in Unraid)
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-2G}
          cpus: ${CPU_LIMIT:-2.0}
        reservations:
          memory: ${MEMORY_RESERVATION:-512M}
          cpus: ${CPU_RESERVATION:-0.5}
