version: '3.8'

services:
  # Official Calibre-Web-Automated
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: cwa-official
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      # Docker Desktop on macOS breaks inotify events between host and container
      # This forces CWA to use polling instead of inotify for reliable file detection
      - NETWORK_SHARE_MODE=true
    ports:
      - "8083:8083"
    volumes:
      # Use local directories for easy access
      - ./cwa-data/config:/config
      - ./cwa-data/library:/calibre-library
      - ./ingest:/cwa-book-ingest
    restart: unless-stopped
    networks:
      - cwa-network

  # Our Flask API (backend only)
  cwa-downloader-api:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: cwa-api
    environment:
      - FLASK_PORT=8084
      - FLASK_HOST=0.0.0.0
      - DEBUG=true
      - APP_ENV=development
      - LOG_LEVEL=DEBUG
      - ENABLE_LOGGING=true
      - BOOK_LANGUAGE=en
      - USE_BOOK_TITLE=true
      - MAX_CONCURRENT_DOWNLOADS=3
      - TZ=America/New_York
      
      # Database paths (shared with CWA)
      - CWA_DB_PATH=/app/data/cwa.db
      
      # CWA connection (internal network)
      - CWA_BASE_URL=http://calibre-web-automated:8083
      - CWA_USERNAME=admin
      - CWA_PASSWORD=admin123
      
      # Anna's Archive Donator Key (optional - speeds up downloads)
      - AA_DONATOR_KEY=A6q86M6EeAZR987D4ci7ywbXhmunZ
      
      # Cloudflare bypass settings
      - USE_CF_BYPASS=true
      
      # DNS settings - use Cloudflare DNS
      - CUSTOM_DNS=cloudflare
      
      # Ingest directory - must match CWA's expected path
      - INGEST_DIR=/app/ingest
      
    ports:
      - "8084:8084"
    volumes:
      # Local directories for easy development
      - ./data:/app/data
      - ./logs:/app/logs
      - ./ingest:/app/ingest
      
      # Access to CWA's library data (read-write for advanced features)
      - ./cwa-data/library:/app/cwa-library
      
    restart: unless-stopped
    depends_on:
      - calibre-web-automated
    networks:
      - cwa-network

networks:
  cwa-network:
    driver: bridge
